### PR TITLE
Add multilib dependencies to README

### PR DESCRIPTION
**Pull request by jmcph4**
This commit adds multilib dependencies for both C and C++ compilers to
the README file to allow building on 64-bit targets.

### CODE REVIEW

**Comment by jmcph4** [comment]
See #89

**Comment by enginmanap** [comment]
let me put this to the docker image so Travis can verify

**Comment by enginmanap** [comment]
I believe this will not be necessary with removing cereal compile

**Comment by jmcph4** [comment]
Closing as underlying issue is fixed without the proposed changes - see #89.

**Pull request closed without merging**
