### PR TITLE
Removing object with its children

### LINKED ISSUE #101: Bullet holes remain behind on coin when picked up
**What happens**
If you shoot a coin, then pick the coin up, the bullet holes are left behind.

**What should happen**
If a coin that's been shot get's picked up, the bullet holes on the coin should disappear with the coin.

### PR DESCRIPTION
**Pull request by onurblt**
Added removing object with its children to World::removeObject(),so attached objects like decals,will be removed after removing the parent.

fixes #101

### CODE REVIEW

**Comment by enginmanap** [comment]
Hey, Thanks for the PR. Can you add an option to the API to remove all children or leave the children alone?

**Comment by onurblt** [comment]
Yes I can . I think you mention about an additional boolean paramater to World::removeObject() ,don't you?

**Comment by enginmanap** [comment]
I think this should be exposed all the way to the user, on the LimonAPI::removeObject, so user can decide whether the remove should cascade or not.

**Comment by onurblt** [comment]
Ok. I will add that.

**Comment by onurblt** [comment]
You are welcome

**Pull request merged**
