### PR TITLE
Fix uninitialised variables in `ModelAsset` class

### PR DESCRIPTION
**Pull request by jmcph4**
This commit provides a definition for `animationNewTime` in
`src/Assets/ModelAsset.cpp`, fixing a compiler warning complaining of
uninitialised values.

See #75

### CODE REVIEW

**Comment by enginmanap** [comment]
Hi,

I think this warning should never been thrown, and it needs a deeper look. Let me check it again.

**Comment by jmcph4** [comment]
@enginmanap that's fine, feel free to knock this one back. I try and keep changes small for that reason.

**Comment by enginmanap** [comment]
Hi,

I am working on another feature that became a blocker for 0.6 release, didn't have time sorry. I will look into this as soon as possible.

**Comment by enginmanap** [comment]
He @jmcph4, bd63a7 doesn't have that warning anymore. Can you please check?

**Pull request merged**
